_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2y$12$r6WzIsit34cKM11s88qBveWPLX1zX64/xRvYCXfZ244DwjPzMWJvi"
  reserved: true
  backend_roles:
    - "admin"
  description: "Platform administrator"

fluent_bit_writer:
  hash: "$2y$12$r6WzIsit34cKM11s88qBveWPLX1zX64/xRvYCXfZ244DwjPzMWJvi"
  reserved: false
  backend_roles:
    - "logwriter"
  description: "Fluent Bit log ingestion service account"

api_user:
  hash: "$2y$12$r6WzIsit34cKM11s88qBveWPLX1zX64/xRvYCXfZ244DwjPzMWJvi"
  reserved: false
  backend_roles:
    - "readall"
    - "alertmanager"
  description: "Analytics API service account"

viewer:
  hash: "$2y$12$r6WzIsit34cKM11s88qBveWPLX1zX64/xRvYCXfZ244DwjPzMWJvi"
  reserved: false
  backend_roles:
    - "readall"
  description: "Read-only dashboard viewer"
